### ISSUE TITLE
HOW-TO FOR INEXPERIENCED USERS!

### ISSUE THREAD

**Issue by aarondsimons** [rebane2001/matterport-dl#95]
I’m a full noob when it comes to Github and Python, so this is how I did it – and it managed to work for me! I hope this can help anyone who needs it.
_Note: I’m using a MacBook with Terminal. **I do not know the steps for Windows.**_

### Step 1: Install Homebrew
1. Open the application “Terminal” on your Mac.
2. Paste this code in: `/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"`
3. Hit enter/return.
4. Follow all of the instructions there, entering your password when needed, and pressing enter/return when needed.
5. Once Homebrew is fully installed, close Terminal.
### Step 2: Install Python using Homebrew
1. Reopen Terminal, and paste this code in: `brew install python3`
2. Follow all instructions.
3. Once Python has been fully installed, close Terminal.
### Step 3: Download the GitHub file
1. Navigate to this page in your browser: https://github.com/mu-ramadan/matterport-dl _(note: this is not the original tool created by rebane2001; it's an updated version by mu-ramadan. The original tool didn't work; THIS updated one is what worked for me!)_
2. Find the green **<> Code** button, click it, then click **Download ZIP**.
3. The ZIP file will now be in your Downloads folder. Move the ZIP file to wherever you're going to want everything to be hosted. For me, this was simply my Documents folder.
4. Double-click the ZIP file to open it and extract the contents. You'll now have a folder called **matterport-dl-main** in your selected location.
5. You're almost there!
### Step 4: Identify your Matterport URL
1. Using the "Developer tools" in your browser of choice, inspect the elements of the page with the Matterport virtual tour and find a link that looks like this: https://my.matterport.com/show/?m=RANDOMLETTERS. There will be a string of uppercase and lowercase letters at the end instead of "RANDOMLETTERS"
2. Once you've found that, copy it and paste it somewhere safe, like in Notes or a Word document.
3. For the remainder of this tutorial, I'm going to call this URL your MATTERPORTURL. ***Whenever you see `MATTERPORTURL` in the codes below, remember to replace this text with your actual URL.**
### Step 5: Identify your folder Pathname
1. In Finder, locate the enclosing folder of the "matterport-dl-main" folder. (Like, for me, this was my Documents)
2. Right-click (two-finger click or control-click) on the "matterport-dl-main" folder.
3. Hold down the **⌥ Option** key, then click **Copy "matterport-dl-main" as Pathname**.
4. Paste this pathname in that safe place (Notes or Word document).
5. It should look something like this: /Users/aaron/Documents/matterport-dl-main (depending on what your enclosing folder is).
6. For the rest of this tutorial (which is almost done!), I'm going to call this pathname your PATHNAME. ***Whenever you see `PATHNAME` in the codes below, remember to replace this text with your actual Pathname.**
### Step 6: Archive your virtual tour
1. Reopen Terminal.
2. Paste in this code: `cd PATHNAME` _(remember to replace PATHNAME with your actual Pathname)_
3. Hit enter/return.
4. Now, paste this code in: `python3 matterport-dl.py "MATTERPORTURL" --advanced-download` _(remember to replace MATTERPORTURL with your actual URL, and make sure the quotes are straight-quotes, not curly-quotes)_
5. Your virtual tour will begin to download fully! This could take a while. Don't close the Terminal app until you receive the "Done!" message at the very end.
### Viewing your archived Matterport tour
1. Whenever you want to view your archived tour (even without internet!), you'll need to do this.
2. Open Terminal and paste in this code: `cd PATHNAME` _(like before, remember to replace PATHNAME with your actual PATHNAME)_
3. Paste in this code: `python3 matterport-dl.py "MATTERPORTURL" 127.0.0.1 8080` _(remember to replace MATTERPORTURL with your actual URL, and make sure the quotes aren't curly-quotes)_
4. Terminal should output something like this: **View in browser: http://127.0.0.1:8080/**
5. Copy that link (http://127.0.0.1:8080/) and paste it into your browser to view your Matterport virtual tour!
6. Note: **You'll need to keep Terminal running while you view your Matterport virtual tour.** Once you're finished viewing, you can close Terminal (and it's ok to click "Terminate").

I really hope this helps the noobs like myself download their Matterport virtual tours! I just finished packing up and moving out of my childhood home and I desperately wanted to archive a version of the house. If some things don't work in the process, scan the other comments on the [Reddit thread](https://www.reddit.com/r/DataHoarder/comments/nycjj4/release_matterportdl_a_tool_for_archiving/?sort=new) for answers. One that helped me was running the `pip3 install requests tqdm -U` command in Terminal when I received an error message in Step 6. Like I said, I honestly know nothing about this whole process, so if you have any questions, I likely won't be able to help – but feel free to leave any comments anyway, and I'll try my best!

Also, sorry if this isn't the right place to put this. I just want to try and help as many people as possible!

**Comment by petruut** [comment]
this is great!! so considerate of you, since i had no clue how to even begin this.

what do you do if you get:

JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 145.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 217.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 231.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 27.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 284.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 324.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 325.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 327.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 330.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 335.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 401.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 408.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 477.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 521.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 573.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 62.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 625.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 648.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 65.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 654.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 662.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 675.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 729.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 858.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 933.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 948.js, will download for you though:)
JS FILE EXTRACTED BUT not known, please file a github issue and tell us to add: 958.js, will download for you though:)

**Comment by petruut** [comment]
how do you fix this?
![image](https://github.com/rebane2001/matterport-dl/assets/15355480/8a7c2c81-6235-4174-8938-763ef37c8249)

**Comment by coolguysa83** [comment]
> how do you fix this? ![image](https://user-images.githubusercontent.com/15355480/261341034-8a7c2c81-6235-4174-8938-763ef37c8249.png)

When you pasted it into terminal, did you make sure you were in the correct directory first, and when you pasted into the quotes, did you remember to include to the model number?  For instance on mine, I had to get to the directory first by typing in cd C:\Users\Default.DESKTOP-6ARHGD2\Downloads\matterport-dl-main new\matterport-dl-main in the command prompt because I had my folder saved in my downloads folder.  Once I got there, I typed in python3 matterport-dl.py "C:\Users\Default.DESKTOP-6ARHGD2\Downloads\matterport-dl-main new\matterport-dl-main\7BZL8BwbVNC" 127.0.0.1 8080 and it worked.

**Comment by Planchee** [comment]
> this is great!! so considerate of you, since i had no clue how to even begin this.
> 
> what do you do if you get:
> 
> JS FILE EXTRACTED BUT not known, please fil...

Hey, not sure if you got it sorted, but the solution was to use Mu-Ramadan's fork. Unfortunately, that apparently stopped working too now (HTTP 401 error).

**Comment by mitchcapper** [comment]
Thanks for this, if there is anything here that might still be valuable for new users please either add to the main README.md or create a GETTING_STARTED.md thanks!

**Comment by GIT-max-ctrl** [comment]
This is an awesome tool - playing around with it out of curiosity and fun.  Can you breakdown step by step once a model is downloaded locally, how to convert to an .exe to then upload and run directly from a webserver? Thanks

**Comment by mitchcapper** [comment]
no, sorry this functionality is either brand new or fairly advanced.   Once downloaded run `matterport-dl.py ModelID 127.0.0.1 8080` and open a browser to http://127.0.0.1:8080.   The only information currently in terms of creating an EXE is in the readme under "Tour Packaging / Single Executable Generation" and may not work.  Running direct from a web server see https://github.com/rebane2001/matterport-dl/blob/main/matterport-dl.py#L847-L984 as you will need to emulate that functionality.

**Comment by TasEolas** [comment]
> This is an awesome tool - playing around with it out of curiosity and fun. Can you breakdown step by step once a model is downloaded locally, how to convert to an .exe to then upload and run directly from a webserver? Thanks

I'm currently trying to troubleshoot the Auto Py to Exe - wondering if anyone has a resource related to the above?

**Comment by CDogs-Fan** [comment]
Sorry for posting in an old thread, but I need some help urgently.  I have a Windows 10 PC and I need to download the 3D tour of my childhood home before the real estate listing is taken down.  So far, I've been unable to get this to work.  I'm unfamiliar with cmd and Python so I'm probably doing something wrong.

Could someone please guide me through the steps so I can do this?

EDIT: When I try to download a Matterport tour, it looks like it tries to download it, but I get a line of purple text in the end that says "AttributeError: 'NoneType' object has no attribute 'group'".
